# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adam/code/IOPL/C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adam/code/IOPL/C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/code/IOPL/C/CMakeFiles /home/adam/code/IOPL/C/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/code/IOPL/C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wonky

# Build rule for target.
wonky: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wonky
.PHONY : wonky

# fast build rule for target.
wonky/fast:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/build
.PHONY : wonky/fast

lex/chonky.o: lex/chonky.c.o

.PHONY : lex/chonky.o

# target to build an object file
lex/chonky.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/chonky.c.o
.PHONY : lex/chonky.c.o

lex/chonky.i: lex/chonky.c.i

.PHONY : lex/chonky.i

# target to preprocess a source file
lex/chonky.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/chonky.c.i
.PHONY : lex/chonky.c.i

lex/chonky.s: lex/chonky.c.s

.PHONY : lex/chonky.s

# target to generate assembly for a file
lex/chonky.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/chonky.c.s
.PHONY : lex/chonky.c.s

lex/chonky_jr.o: lex/chonky_jr.c.o

.PHONY : lex/chonky_jr.o

# target to build an object file
lex/chonky_jr.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/chonky_jr.c.o
.PHONY : lex/chonky_jr.c.o

lex/chonky_jr.i: lex/chonky_jr.c.i

.PHONY : lex/chonky_jr.i

# target to preprocess a source file
lex/chonky_jr.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/chonky_jr.c.i
.PHONY : lex/chonky_jr.c.i

lex/chonky_jr.s: lex/chonky_jr.c.s

.PHONY : lex/chonky_jr.s

# target to generate assembly for a file
lex/chonky_jr.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/chonky_jr.c.s
.PHONY : lex/chonky_jr.c.s

lex/lexer.o: lex/lexer.c.o

.PHONY : lex/lexer.o

# target to build an object file
lex/lexer.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/lexer.c.o
.PHONY : lex/lexer.c.o

lex/lexer.i: lex/lexer.c.i

.PHONY : lex/lexer.i

# target to preprocess a source file
lex/lexer.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/lexer.c.i
.PHONY : lex/lexer.c.i

lex/lexer.s: lex/lexer.c.s

.PHONY : lex/lexer.s

# target to generate assembly for a file
lex/lexer.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/lexer.c.s
.PHONY : lex/lexer.c.s

lex/preprocessing.o: lex/preprocessing.c.o

.PHONY : lex/preprocessing.o

# target to build an object file
lex/preprocessing.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/preprocessing.c.o
.PHONY : lex/preprocessing.c.o

lex/preprocessing.i: lex/preprocessing.c.i

.PHONY : lex/preprocessing.i

# target to preprocess a source file
lex/preprocessing.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/preprocessing.c.i
.PHONY : lex/preprocessing.c.i

lex/preprocessing.s: lex/preprocessing.c.s

.PHONY : lex/preprocessing.s

# target to generate assembly for a file
lex/preprocessing.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/lex/preprocessing.c.s
.PHONY : lex/preprocessing.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/main.c.s
.PHONY : main.c.s

misc/map.o: misc/map.c.o

.PHONY : misc/map.o

# target to build an object file
misc/map.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/map.c.o
.PHONY : misc/map.c.o

misc/map.i: misc/map.c.i

.PHONY : misc/map.i

# target to preprocess a source file
misc/map.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/map.c.i
.PHONY : misc/map.c.i

misc/map.s: misc/map.c.s

.PHONY : misc/map.s

# target to generate assembly for a file
misc/map.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/map.c.s
.PHONY : misc/map.c.s

misc/print.o: misc/print.c.o

.PHONY : misc/print.o

# target to build an object file
misc/print.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/print.c.o
.PHONY : misc/print.c.o

misc/print.i: misc/print.c.i

.PHONY : misc/print.i

# target to preprocess a source file
misc/print.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/print.c.i
.PHONY : misc/print.c.i

misc/print.s: misc/print.c.s

.PHONY : misc/print.s

# target to generate assembly for a file
misc/print.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/print.c.s
.PHONY : misc/print.c.s

misc/queue.o: misc/queue.c.o

.PHONY : misc/queue.o

# target to build an object file
misc/queue.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/queue.c.o
.PHONY : misc/queue.c.o

misc/queue.i: misc/queue.c.i

.PHONY : misc/queue.i

# target to preprocess a source file
misc/queue.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/queue.c.i
.PHONY : misc/queue.c.i

misc/queue.s: misc/queue.c.s

.PHONY : misc/queue.s

# target to generate assembly for a file
misc/queue.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/queue.c.s
.PHONY : misc/queue.c.s

misc/stack.o: misc/stack.c.o

.PHONY : misc/stack.o

# target to build an object file
misc/stack.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/stack.c.o
.PHONY : misc/stack.c.o

misc/stack.i: misc/stack.c.i

.PHONY : misc/stack.i

# target to preprocess a source file
misc/stack.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/stack.c.i
.PHONY : misc/stack.c.i

misc/stack.s: misc/stack.c.s

.PHONY : misc/stack.s

# target to generate assembly for a file
misc/stack.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/misc/stack.c.s
.PHONY : misc/stack.c.s

parse/parse_declaration.o: parse/parse_declaration.c.o

.PHONY : parse/parse_declaration.o

# target to build an object file
parse/parse_declaration.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_declaration.c.o
.PHONY : parse/parse_declaration.c.o

parse/parse_declaration.i: parse/parse_declaration.c.i

.PHONY : parse/parse_declaration.i

# target to preprocess a source file
parse/parse_declaration.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_declaration.c.i
.PHONY : parse/parse_declaration.c.i

parse/parse_declaration.s: parse/parse_declaration.c.s

.PHONY : parse/parse_declaration.s

# target to generate assembly for a file
parse/parse_declaration.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_declaration.c.s
.PHONY : parse/parse_declaration.c.s

parse/parse_expression.o: parse/parse_expression.c.o

.PHONY : parse/parse_expression.o

# target to build an object file
parse/parse_expression.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_expression.c.o
.PHONY : parse/parse_expression.c.o

parse/parse_expression.i: parse/parse_expression.c.i

.PHONY : parse/parse_expression.i

# target to preprocess a source file
parse/parse_expression.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_expression.c.i
.PHONY : parse/parse_expression.c.i

parse/parse_expression.s: parse/parse_expression.c.s

.PHONY : parse/parse_expression.s

# target to generate assembly for a file
parse/parse_expression.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_expression.c.s
.PHONY : parse/parse_expression.c.s

parse/parse_statement.o: parse/parse_statement.c.o

.PHONY : parse/parse_statement.o

# target to build an object file
parse/parse_statement.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_statement.c.o
.PHONY : parse/parse_statement.c.o

parse/parse_statement.i: parse/parse_statement.c.i

.PHONY : parse/parse_statement.i

# target to preprocess a source file
parse/parse_statement.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_statement.c.i
.PHONY : parse/parse_statement.c.i

parse/parse_statement.s: parse/parse_statement.c.s

.PHONY : parse/parse_statement.s

# target to generate assembly for a file
parse/parse_statement.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_statement.c.s
.PHONY : parse/parse_statement.c.s

parse/parse_translation_unit.o: parse/parse_translation_unit.c.o

.PHONY : parse/parse_translation_unit.o

# target to build an object file
parse/parse_translation_unit.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_translation_unit.c.o
.PHONY : parse/parse_translation_unit.c.o

parse/parse_translation_unit.i: parse/parse_translation_unit.c.i

.PHONY : parse/parse_translation_unit.i

# target to preprocess a source file
parse/parse_translation_unit.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_translation_unit.c.i
.PHONY : parse/parse_translation_unit.c.i

parse/parse_translation_unit.s: parse/parse_translation_unit.c.s

.PHONY : parse/parse_translation_unit.s

# target to generate assembly for a file
parse/parse_translation_unit.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/parse/parse_translation_unit.c.s
.PHONY : parse/parse_translation_unit.c.s

semantics/ast.o: semantics/ast.c.o

.PHONY : semantics/ast.o

# target to build an object file
semantics/ast.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/ast.c.o
.PHONY : semantics/ast.c.o

semantics/ast.i: semantics/ast.c.i

.PHONY : semantics/ast.i

# target to preprocess a source file
semantics/ast.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/ast.c.i
.PHONY : semantics/ast.c.i

semantics/ast.s: semantics/ast.c.s

.PHONY : semantics/ast.s

# target to generate assembly for a file
semantics/ast.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/ast.c.s
.PHONY : semantics/ast.c.s

semantics/denoted.o: semantics/denoted.c.o

.PHONY : semantics/denoted.o

# target to build an object file
semantics/denoted.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/denoted.c.o
.PHONY : semantics/denoted.c.o

semantics/denoted.i: semantics/denoted.c.i

.PHONY : semantics/denoted.i

# target to preprocess a source file
semantics/denoted.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/denoted.c.i
.PHONY : semantics/denoted.c.i

semantics/denoted.s: semantics/denoted.c.s

.PHONY : semantics/denoted.s

# target to generate assembly for a file
semantics/denoted.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/denoted.c.s
.PHONY : semantics/denoted.c.s

semantics/location.o: semantics/location.c.o

.PHONY : semantics/location.o

# target to build an object file
semantics/location.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/location.c.o
.PHONY : semantics/location.c.o

semantics/location.i: semantics/location.c.i

.PHONY : semantics/location.i

# target to preprocess a source file
semantics/location.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/location.c.i
.PHONY : semantics/location.c.i

semantics/location.s: semantics/location.c.s

.PHONY : semantics/location.s

# target to generate assembly for a file
semantics/location.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/location.c.s
.PHONY : semantics/location.c.s

semantics/program.o: semantics/program.c.o

.PHONY : semantics/program.o

# target to build an object file
semantics/program.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/program.c.o
.PHONY : semantics/program.c.o

semantics/program.i: semantics/program.c.i

.PHONY : semantics/program.i

# target to preprocess a source file
semantics/program.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/program.c.i
.PHONY : semantics/program.c.i

semantics/program.s: semantics/program.c.s

.PHONY : semantics/program.s

# target to generate assembly for a file
semantics/program.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/program.c.s
.PHONY : semantics/program.c.s

semantics/scope.o: semantics/scope.c.o

.PHONY : semantics/scope.o

# target to build an object file
semantics/scope.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/scope.c.o
.PHONY : semantics/scope.c.o

semantics/scope.i: semantics/scope.c.i

.PHONY : semantics/scope.i

# target to preprocess a source file
semantics/scope.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/scope.c.i
.PHONY : semantics/scope.c.i

semantics/scope.s: semantics/scope.c.s

.PHONY : semantics/scope.s

# target to generate assembly for a file
semantics/scope.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/scope.c.s
.PHONY : semantics/scope.c.s

semantics/semantics.o: semantics/semantics.c.o

.PHONY : semantics/semantics.o

# target to build an object file
semantics/semantics.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/semantics.c.o
.PHONY : semantics/semantics.c.o

semantics/semantics.i: semantics/semantics.c.i

.PHONY : semantics/semantics.i

# target to preprocess a source file
semantics/semantics.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/semantics.c.i
.PHONY : semantics/semantics.c.i

semantics/semantics.s: semantics/semantics.c.s

.PHONY : semantics/semantics.s

# target to generate assembly for a file
semantics/semantics.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/semantics.c.s
.PHONY : semantics/semantics.c.s

semantics/type.o: semantics/type.c.o

.PHONY : semantics/type.o

# target to build an object file
semantics/type.c.o:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/type.c.o
.PHONY : semantics/type.c.o

semantics/type.i: semantics/type.c.i

.PHONY : semantics/type.i

# target to preprocess a source file
semantics/type.c.i:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/type.c.i
.PHONY : semantics/type.c.i

semantics/type.s: semantics/type.c.s

.PHONY : semantics/type.s

# target to generate assembly for a file
semantics/type.c.s:
	$(MAKE) -f CMakeFiles/wonky.dir/build.make CMakeFiles/wonky.dir/semantics/type.c.s
.PHONY : semantics/type.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... wonky"
	@echo "... edit_cache"
	@echo "... lex/chonky.o"
	@echo "... lex/chonky.i"
	@echo "... lex/chonky.s"
	@echo "... lex/chonky_jr.o"
	@echo "... lex/chonky_jr.i"
	@echo "... lex/chonky_jr.s"
	@echo "... lex/lexer.o"
	@echo "... lex/lexer.i"
	@echo "... lex/lexer.s"
	@echo "... lex/preprocessing.o"
	@echo "... lex/preprocessing.i"
	@echo "... lex/preprocessing.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... misc/map.o"
	@echo "... misc/map.i"
	@echo "... misc/map.s"
	@echo "... misc/print.o"
	@echo "... misc/print.i"
	@echo "... misc/print.s"
	@echo "... misc/queue.o"
	@echo "... misc/queue.i"
	@echo "... misc/queue.s"
	@echo "... misc/stack.o"
	@echo "... misc/stack.i"
	@echo "... misc/stack.s"
	@echo "... parse/parse_declaration.o"
	@echo "... parse/parse_declaration.i"
	@echo "... parse/parse_declaration.s"
	@echo "... parse/parse_expression.o"
	@echo "... parse/parse_expression.i"
	@echo "... parse/parse_expression.s"
	@echo "... parse/parse_statement.o"
	@echo "... parse/parse_statement.i"
	@echo "... parse/parse_statement.s"
	@echo "... parse/parse_translation_unit.o"
	@echo "... parse/parse_translation_unit.i"
	@echo "... parse/parse_translation_unit.s"
	@echo "... semantics/ast.o"
	@echo "... semantics/ast.i"
	@echo "... semantics/ast.s"
	@echo "... semantics/denoted.o"
	@echo "... semantics/denoted.i"
	@echo "... semantics/denoted.s"
	@echo "... semantics/location.o"
	@echo "... semantics/location.i"
	@echo "... semantics/location.s"
	@echo "... semantics/program.o"
	@echo "... semantics/program.i"
	@echo "... semantics/program.s"
	@echo "... semantics/scope.o"
	@echo "... semantics/scope.i"
	@echo "... semantics/scope.s"
	@echo "... semantics/semantics.o"
	@echo "... semantics/semantics.i"
	@echo "... semantics/semantics.s"
	@echo "... semantics/type.o"
	@echo "... semantics/type.i"
	@echo "... semantics/type.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

